steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sharkops-239501/recipe-builder-image:v2', '.']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sharkops-239501/recipe-builder-image:v2']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/shark-ops-deployment', 'shark-ops-deployment=gcr.io/sharkops-239501/recipe-builder-image:v2']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east4-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=shark-ops-cluster'
timeout: 660s
tags: ['mytag1', 'mytag2']
images: ['gcr.io/sharkops-239501/recipe-builder-image:v2']