steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/sharkops-239501/recipe-builder-image', '.']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/sharkops-239501/recipe-builder-image']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/shark-deployment', 'nginx=gcr.io/sharkops-239501/recipe-builder-image']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east4-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=shark-cluster-2'
timeout: 660s
tags: ['mytag1', 'mytag2']
images: ['gcr.io/sharkops-239501/recipebuilderimage']